### ISSUE TITLE
Dateiendungen

### ISSUE THREAD

**Issue by FelixMay** [FelixMay/FragFrame_1#3]
Wir sollten konsistente Dateiendungen verwenden. Bei mir scheint es `.R` und bei dir `.r`zu sein.
Was sollen wir nehmen? Mein RStudio macht standardmäßig `.R`. Darum bin ich natürlich dafür :o)

Das ist natürlich totaler Kleinkram

**Comment by KatharinaGerstner** [comment]
Da bin ich gefühlsneutral. Mach das!

**Comment by FelixMay** [comment]
Erledigt
