### ISSUE TITLE
If abfragen zu einzelnen Dateien

### ISSUE THREAD

**Issue by FelixMay** [FelixMay/FragFrame_1#4]
In der Datei `01.1_CalculateBDFromAbundance.R` gibt es if Abfragen zu einzelnen Dateinamen. Das sieht gefährlich und komisch aus. Ich vermute, stattdessen sollte in den Dateien selber etwas geändert werden, damit das Datenformat konsistent ist.

**Comment by KatharinaGerstner** [comment]
Der Vorschlag das in den Dateien zu ändern wurde von Mario abgelehnt, um Details zu erhalten. Das sind edges vs interior in Dauber und Didham und three sites per fragment in Schnitzler. Mit den if-Abfragen habe ich diese Daten gepoolt. Siehe auch Mail Austausch vom 28.11.17. Ich habe ein paar Zeilen zur Dokumentation hinzugefügt.
